import express from 'express';
import customerRoutes from './customerRoutes.ts';
import transactionRoutes from './transactionRoutes.ts';
import invoiceRoutes from './invoiceRoutes.ts';
import productRoutes from './productRoutes.ts';
import paymentRoutes from './paymentRoutes.ts';
import staffRoutes from './staffRoutes.ts';
import voucherRoutes from './voucherRoutes.ts';
import authRoutes from './authRoutes.ts';
import subscriptionRoutes from './subscriptionRoutes.ts';
import adminRoutes from './adminRoutes.ts';
import settingsRoutes from './settingsRoutes.ts';
import notificationRoutes from './notificationRoutes.ts';
import reminderRoutes from './reminderRoutes.ts';
import landingRoutes from './landingRoutes.ts';
import ledgerRoutes from './ledgerRoutes.ts';
import vendorRoutes from './vendorRoutes.ts';
import inventoryRoutes from './inventoryRoutes.ts';
import analyticsRoutes from './analyticsRoutes.ts';
import shopRoutes from './shopRoutes.ts';
import whatsappRoutes from './whatsappRoutes.ts';
import campaignRoutes from './campaignRoutes.ts';
import aiRoutes from './aiRoutes.ts';
import expenseRoutes from './expenseRoutes.ts';
import taxRoutes from './taxRoutes.ts';
import warehouseRoutes from './warehouseRoutes.ts';
import payrollRoutes from './payrollRoutes.ts';
import reportRoutes from './reportRoutes.ts';
import publicRoutes from './publicRoutes.ts';
import loanRoutes from './loanRoutes.ts';
import returnRoutes from './returnRoutes.ts';

const router = express.Router();

router.use('/customers', customerRoutes);
router.use('/ledger', ledgerRoutes);
router.use('/transactions', transactionRoutes);
router.use('/invoices', invoiceRoutes);
router.use('/products', productRoutes);
router.use('/payments', paymentRoutes);
router.use('/staff', staffRoutes);
router.use('/vouchers', voucherRoutes);
router.use('/auth', authRoutes);
router.use('/subscription', subscriptionRoutes);
router.use('/admin', adminRoutes);
router.use('/settings', settingsRoutes);
router.use('/notifications', notificationRoutes);
router.use('/reminders', reminderRoutes);
router.use('/landing', landingRoutes);
router.use('/vendors', vendorRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/shops', shopRoutes);
router.use('/whatsapp', whatsappRoutes);
router.use('/campaigns', campaignRoutes);
router.use('/ai', aiRoutes);
router.use('/expenses', expenseRoutes);
router.use('/tax', taxRoutes);
router.use('/warehouses', warehouseRoutes);
router.use('/payroll', payrollRoutes);
router.use('/reports', reportRoutes);
router.use('/public', publicRoutes);
router.use('/loans', loanRoutes);
router.use('/returns', returnRoutes);

export default router;
