import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Language = 
  | 'en' | 'hi' | 'bn' | 'te' | 'mr' | 'ta' | 'ur' | 'gu' | 'kn' | 'ml' | 'or' | 'pa' 
  | 'as' | 'mai' | 'sat' | 'ks' | 'ne' | 'kok' | 'sd' | 'doi' | 'mni' | 'sa' | 'brx';

interface LanguageConfig {
  name: string;
  nativeName: string;
}

export const languages: Record<Language, LanguageConfig> = {
  en: { name: 'English', nativeName: 'English' },
  hi: { name: 'Hindi', nativeName: 'हिन्दी' },
  bn: { name: 'Bengali', nativeName: 'বাংলা' },
  te: { name: 'Telugu', nativeName: 'తెలుగు' },
  mr: { name: 'Marathi', nativeName: 'मराठी' },
  ta: { name: 'Tamil', nativeName: 'தமிழ்' },
  ur: { name: 'Urdu', nativeName: 'اردو' },
  gu: { name: 'Gujarati', nativeName: 'ગુજરાતી' },
  kn: { name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  ml: { name: 'Malayalam', nativeName: 'മലയാളം' },
  or: { name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  pa: { name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  as: { name: 'Assamese', nativeName: 'অসমীয়া' },
  mai: { name: 'Maithili', nativeName: 'मैथिली' },
  sat: { name: 'Santali', nativeName: 'संताली' },
  ks: { name: 'Kashmiri', nativeName: 'कॉशुर' },
  ne: { name: 'Nepali', nativeName: 'नेपाली' },
  kok: { name: 'Konkani', nativeName: 'कोंकणी' },
  sd: { name: 'Sindhi', nativeName: 'سنڌي' },
  doi: { name: 'Dogri', nativeName: 'डोगरी' },
  mni: { name: 'Manipuri', nativeName: 'মৈতৈলোন্' },
  sa: { name: 'Sanskrit', nativeName: 'संस्कृतम्' },
  brx: { name: 'Bodo', nativeName: 'बड़ो' },
};

const translations: Record<Language, any> = {
  en: {
    dashboard: 'Dashboard',
    khata: 'Digital Khata',
    vendors: 'Vendor Khata',
    invoices: 'Invoices & Billing',
    inventory: 'Inventory',
    payments: 'Payments & QR',
    reports: 'Reports',
    staff: 'Staff Management',
    ai: 'AI Intelligence',
    store: 'Online Store',
    vouchers: 'Vouchers',
    community: 'Community',
    subscription: 'Subscription',
    settings: 'Settings',
    createBill: 'Create Bill',
    logout: 'Logout',
    welcome: 'Welcome back',
    totalSales: 'Total Sales',
    totalBalance: 'Total Balance',
    activeOrders: 'Active Orders',
    lowStock: 'Low Stock Items',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    khata: 'डिजिटल खाता',
    vendors: 'वेंडर खाता',
    invoices: 'इनवॉइस और बिलिंग',
    inventory: 'इन्वेंट्री',
    payments: 'भुगतान और QR',
    reports: 'रिपोर्ट',
    staff: 'स्टाफ मैनेजमेंट',
    ai: 'AI इंटेलिजेंस',
    store: 'ऑनलाइन स्टोर',
    vouchers: 'वाउचर',
    community: 'कम्युनिटी',
    subscription: 'सब्सक्रिप्शन',
    settings: 'सेटिंग्स',
    createBill: 'बिल बनाएं',
    logout: 'लॉगआउट',
    welcome: 'स्वागत है',
    totalSales: 'कुल बिक्री',
    totalBalance: 'कुल शेष',
    activeOrders: 'सक्रिय ऑर्डर',
    lowStock: 'कम स्टॉक वाली वस्तुएं',
  },
  bn: {
    dashboard: 'ড্যাশবোর্ড',
    khata: 'খাতা',
    invoices: 'ইনভয়েস ও বিলিং',
    inventory: 'ইনভেন্টরি',
    payments: 'পেমেন্ট ও QR',
    reports: 'রিপোর্ট',
    staff: 'স্টাফ ম্যানেজমেন্ট',
    ai: 'AI ইন্টেলিজেন্স',
    store: 'অনলাইন স্টোর',
    vouchers: 'ভাউচার',
    community: 'কমিউনিটি',
    subscription: 'সাবস্ক্রিপশন',
    settings: 'সেটিংস',
    createBill: 'বিল তৈরি করুন',
    logout: 'লগআউট',
  },
  te: {
    dashboard: 'డాష్‌బోర్డ్',
    khata: 'ఖాతా',
    invoices: 'ఇన్వాయిస్ & బిల్లింగ్',
    inventory: 'ఇన్వెంటరీ',
    payments: 'చెల్లింపులు & QR',
    reports: 'నివేదికలు',
    staff: 'స్టాఫ్ మేనేజ్‌మెంట్',
    ai: 'AI ఇంటెలిజెన్స్',
    store: 'ఆన్‌లైన్ స్టోర్',
    vouchers: 'వోచర్లు',
    community: 'కమ్యూనిటీ',
    subscription: 'సబ్‌స్క్రిప్షన్',
    settings: 'సెట్టింగ్లు',
    createBill: 'బిల్లు సృష్టించు',
    logout: 'లాగ్అవుట్',
  },
  mr: {
    dashboard: 'डॅशबोर्ड',
    khata: 'खाते',
    invoices: 'इनव्हॉइस आणि बिलिंग',
    inventory: 'इन्व्हेंटरी',
    payments: 'पेमेंट आणि QR',
    reports: 'रिपोर्ट्स',
    staff: 'स्टाफ मॅनेजमेंट',
    ai: 'AI इंटेलिजन्स',
    store: 'ऑनलाइन स्टोअर',
    vouchers: 'वाउचर्स',
    community: 'कम्युनिटी',
    subscription: 'सबस्क्रिप्शन',
    settings: 'सेटिंग्ज',
    createBill: 'बिल तयार करा',
    logout: 'लॉगआउट',
  },
  ta: {
    dashboard: 'டாஷ்போர்டு',
    khata: 'கணக்கு',
    invoices: 'இன்வாய்ஸ் & பில்லிங்',
    inventory: 'சரக்கு இருப்பு',
    payments: 'கொடுப்பனவுகள் & QR',
    reports: 'அறிக்கைகள்',
    staff: 'பணியாளர் மேலாண்மை',
    ai: 'AI நுண்ணறிவு',
    store: 'ஆன்லைன் ஸ்டோர்',
    vouchers: 'வவுச்சர்கள்',
    community: 'சமூகம்',
    subscription: 'சந்தா',
    settings: 'அமைப்புகள்',
    createBill: 'பில் உருவாக்கவும்',
    logout: 'வெளியேறு',
  },
  gu: {
    dashboard: 'ડેશબોર્ડ',
    khata: 'ખાતું',
    invoices: 'ઈનવોઈસ અને બિલિંગ',
    inventory: 'ઈન્વેન્ટરી',
    payments: 'ચુકવણી અને QR',
    reports: 'રિપોર્ટ',
    staff: 'સ્ટાફ મેનેજમેન્ટ',
    ai: 'AI ઇન્ટેલિજન્સ',
    store: 'ઓનલાઇન સ્ટોર',
    vouchers: 'વાઉચર',
    community: 'કમ્યુનિટી',
    subscription: 'સબ્સ્ક્રિપ્શન',
    settings: 'સેટિંગ્સ',
    createBill: 'બિલ બનાવો',
    logout: 'લોગઆઉટ',
  },
  kn: {
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    khata: 'ಖಾತೆ',
    invoices: 'ಇನ್ವಾಯ್ಸ್ ಮತ್ತು ಬಿಲ್ಲಿಂಗ್',
    inventory: 'ಇನ್ವೆಂಟರಿ',
    payments: 'ಪಾವತಿಗಳು ಮತ್ತು QR',
    reports: 'ವರದಿಗಳು',
    staff: 'ಸಿಬ್ಬಂದಿ ನಿರ್ವಹಣೆ',
    ai: 'AI ಇಂಟೆಲಿಜೆನ್ಸ್',
    store: 'ಆನ್‌ಲೈನ್ ಸ್ಟೋರ್',
    vouchers: 'ವೋಚರ್‌ಗಳು',
    community: 'ಸಮುದಾಯ',
    subscription: 'ಚಂದಾದಾರಿಕೆ',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    createBill: 'ಬಿಲ್ ರಚಿಸಿ',
    logout: 'ಲಾಗ್ ಔಟ್',
  },
  ml: {
    dashboard: 'ഡാഷ്ബോർഡ്',
    khata: 'ഖാത്ത',
    invoices: 'ഇൻവോയ്സ് & ബില്ലിംഗ്',
    inventory: 'ഇൻവെന്ററി',
    payments: 'പേയ്‌മെന്റുകൾ & QR',
    reports: 'റിപ്പോർട്ടുകൾ',
    staff: 'സ്റ്റാഫ് മാനേജ്‌മെന്റ്',
    ai: 'AI ഇന്റലിജൻസ്',
    store: 'ഓൺലൈൻ സ്റ്റോർ',
    vouchers: 'വൗച്ചറുകൾ',
    community: 'കമ്മ്യൂണിറ്റി',
    subscription: 'സബ്‌സ്‌ക്രിപ്‌ഷൻ',
    settings: 'ക്രമീകരണങ്ങൾ',
    createBill: 'ബിൽ തയ്യാറാക്കുക',
    logout: 'ലോഗ് ഔട്ട്',
  },
  pa: {
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    khata: 'ਖਾਤਾ',
    invoices: 'ਇਨਵੌਇਸ ਅਤੇ ਬਿਲਿੰਗ',
    inventory: 'ਇਨਵੈਂਟਰੀ',
    payments: 'ਭੁਗਤਾਨ ਅਤੇ QR',
    reports: 'ਰਿਪੋਰਟਾਂ',
    staff: 'ਸਟਾਫ ਪ੍ਰਬੰਧਨ',
    ai: 'AI ਇੰਟੈਲੀਜੈਂਸ',
    store: 'ਔਨਲਾਈਨ ਸਟੋਰ',
    vouchers: 'ਵਾਊਚਰ',
    community: 'ਕਮਿਊਨਿਟੀ',
    subscription: 'ਸਬਸਕ੍ਰਿਪਸ਼ਨ',
    settings: 'ਸੈਟਿੰਗਾਂ',
    createBill: 'ਬਿੱਲ ਬਣਾਓ',
    logout: 'ਲੌਗਆਉਟ',
  },
  ur: {
    dashboard: 'ڈیش بورڈ',
    khata: 'کھاتا',
    invoices: 'انوائس اور بلنگ',
    inventory: 'انوینٹری',
    payments: 'ادائیگی اور QR',
    reports: 'رپورٹیں',
    staff: 'اسٹاف مینجمنٹ',
    ai: 'AI انٹیلی جنس',
    store: 'آن لائن اسٹور',
    vouchers: 'واؤچرز',
    community: 'کمیونٹی',
    subscription: 'سبسکرپشن',
    settings: 'ترتیبات',
    createBill: 'بل بنائیں',
    logout: 'لاگ آؤٹ',
  },
  or: {
    dashboard: 'ଡ୍ୟାସବୋର୍ଡ',
    khata: 'ଖାତା',
    invoices: 'ଇନଭଏସ୍ ଏବଂ ବିଲିଂ',
    inventory: 'ଇନଭେଣ୍ଟୋਰୀ',
    payments: 'ପେମେଣ୍ଟ ଏବଂ QR',
    reports: 'ରିପୋର୍ଟ',
    staff: 'ଷ୍ଟାଫ୍ ମ୍ୟାନେଜମେଣ୍ଟ',
    ai: 'AI ଇଣ୍ଟେଲିଜେନ୍ସ',
    store: 'ଅନଲାଇନ୍ ଷ୍ଟୋର୍',
    vouchers: 'ଭାଉଚର୍',
    community: 'କମ୍ୟୁନିଟି',
    subscription: 'ସବସ୍କ୍ରିପସନ୍',
    settings: 'ସେଟିଂସ',
    createBill: 'ବିଲ୍ ପ୍ରସ୍ତୁତ କରନ୍ତୁ',
    logout: 'ଲଗଆଉଟ୍',
  },
  as: {}, mai: {}, sat: {}, ks: {}, ne: {}, kok: {}, sd: {}, doi: {}, mni: {}, sa: {}, brx: {},
};

interface LanguageState {
  currentLanguage: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      currentLanguage: 'en',
      setLanguage: (lang) => set({ currentLanguage: lang }),
      t: (key) => {
        const lang = get().currentLanguage;
        return translations[lang]?.[key] || translations['en'][key] || key;
      },
    }),
    {
      name: 'dukandost-language',
    }
  )
);
