// ===================================
// DukanDost Pro - Realistic Mock Data
// ===================================

export const mockCustomers = [
  {
    id: 'c1', _id: 'c1',
    name: 'Rajesh Kumar',
    phone: '+91 98765 43210',
    balance: 4500,
    initials: 'RK',
    color: 'bg-orange-100 text-orange-700',
    status: 'Overdue' as const,
    lastTransactionDate: '15 Apr 2026',
  },
  {
    id: 'c2', _id: 'c2',
    name: 'Suresh Sharma',
    phone: '+91 91234 56789',
    balance: 18500,
    initials: 'SS',
    color: 'bg-red-100 text-red-700',
    status: 'Overdue' as const,
    lastTransactionDate: '10 Apr 2026',
  },
  {
    id: 'c3', _id: 'c3',
    name: 'Amit Gupta',
    phone: '+91 88765 43210',
    balance: 2200,
    initials: 'AG',
    color: 'bg-blue-100 text-blue-700',
    status: 'Udhaar' as const,
    lastTransactionDate: '20 Apr 2026',
  },
  {
    id: 'c4', _id: 'c4',
    name: 'Priya Singh',
    phone: '+91 77654 32109',
    balance: 0,
    initials: 'PS',
    color: 'bg-green-100 text-green-700',
    status: 'Up-to-date' as const,
    lastTransactionDate: '25 Apr 2026',
  },
  {
    id: 'c5', _id: 'c5',
    name: 'Vikram Patel',
    phone: '+91 99876 54321',
    balance: 3800,
    initials: 'VP',
    color: 'bg-purple-100 text-purple-700',
    status: 'Udhaar' as const,
    lastTransactionDate: '18 Apr 2026',
  },
  {
    id: 'c6', _id: 'c6',
    name: 'Sunita Devi',
    phone: '+91 95432 10987',
    balance: 0,
    initials: 'SD',
    color: 'bg-teal-100 text-teal-700',
    status: 'Up-to-date' as const,
    lastTransactionDate: '26 Apr 2026',
  },
  {
    id: 'c7', _id: 'c7',
    name: 'Mohan Lal',
    phone: '+91 87654 32198',
    balance: 7200,
    initials: 'ML',
    color: 'bg-amber-100 text-amber-700',
    status: 'Overdue' as const,
    lastTransactionDate: '5 Apr 2026',
  },
  {
    id: 'c8', _id: 'c8',
    name: 'Kavitha Rao',
    phone: '+91 90123 45678',
    balance: 1500,
    initials: 'KR',
    color: 'bg-pink-100 text-pink-700',
    status: 'Udhaar' as const,
    lastTransactionDate: '22 Apr 2026',
  },
  {
    id: 'c9', _id: 'c9',
    name: 'Deepak Verma',
    phone: '+91 98012 34567',
    balance: 0,
    initials: 'DV',
    color: 'bg-indigo-100 text-indigo-700',
    status: 'Up-to-date' as const,
    lastTransactionDate: '24 Apr 2026',
  },
  {
    id: 'c10', _id: 'c10',
    name: 'Pooja Mehta',
    phone: '+91 97890 12345',
    balance: 9800,
    initials: 'PM',
    color: 'bg-rose-100 text-rose-700',
    status: 'Overdue' as const,
    lastTransactionDate: '8 Apr 2026',
  },
];

export const mockTransactions = [
  {
    id: 't1', _id: 't1',
    createdAt: '26 Apr 2026, 10:30 AM',
    customerId: 'c1',
    customerName: 'Rajesh Kumar',
    customerInitials: 'RK',
    customerColor: 'bg-orange-100 text-orange-700',
    amount: 1500,
    type: 'Liya' as const,
    note: 'Monthly grocery payment',
  },
  {
    id: 't2', _id: 't2',
    createdAt: '25 Apr 2026, 03:15 PM',
    customerId: 'c2',
    customerName: 'Suresh Sharma',
    customerInitials: 'SS',
    customerColor: 'bg-red-100 text-red-700',
    amount: 4200,
    type: 'Diya' as const,
    note: 'Atta, Cheeni, Tel',
  },
  {
    id: 't3', _id: 't3',
    createdAt: '25 Apr 2026, 11:00 AM',
    customerId: 'c4',
    customerName: 'Priya Singh',
    customerInitials: 'PS',
    customerColor: 'bg-green-100 text-green-700',
    amount: 850,
    type: 'Liya' as const,
    note: 'Cash payment cleared',
  },
  {
    id: 't4', _id: 't4',
    createdAt: '24 Apr 2026, 06:45 PM',
    customerId: 'c3',
    customerName: 'Amit Gupta',
    customerInitials: 'AG',
    customerColor: 'bg-blue-100 text-blue-700',
    amount: 2200,
    type: 'Diya' as const,
    note: 'Rice 25kg, Dal 5kg',
  },
  {
    id: 't5', _id: 't5',
    createdAt: '24 Apr 2026, 02:30 PM',
    customerId: 'c5',
    customerName: 'Vikram Patel',
    customerInitials: 'VP',
    customerColor: 'bg-purple-100 text-purple-700',
    amount: 600,
    type: 'Liya' as const,
    note: 'Partial payment',
  },
  {
    id: 't6', _id: 't6',
    createdAt: '23 Apr 2026, 09:00 AM',
    customerId: 'c7',
    customerName: 'Mohan Lal',
    customerInitials: 'ML',
    customerColor: 'bg-amber-100 text-amber-700',
    amount: 3500,
    type: 'Diya' as const,
    note: 'Monthly staples',
  },
  {
    id: 't7', _id: 't7',
    createdAt: '22 Apr 2026, 04:20 PM',
    customerId: 'c8',
    customerName: 'Kavitha Rao',
    customerInitials: 'KR',
    customerColor: 'bg-pink-100 text-pink-700',
    amount: 1500,
    type: 'Diya' as const,
    note: 'Medicines + groceries',
  },
  {
    id: 't8', _id: 't8',
    createdAt: '22 Apr 2026, 10:45 AM',
    customerId: 'c10',
    customerName: 'Pooja Mehta',
    customerInitials: 'PM',
    customerColor: 'bg-rose-100 text-rose-700',
    amount: 2800,
    type: 'Liya' as const,
    note: 'Advance payment',
  },
];

export const mockProducts = [
  {
    id: 'p1',
    name: 'Aashirvaad Atta 5kg',
    category: 'Groceries',
    sku: 'SKU-ATT-001',
    stock: 45,
    price: 245,
    status: 'IN STOCK' as const,
    icon: '🌾',
  },
  {
    id: 'p2',
    name: 'Fortune Sunflower Oil 1L',
    category: 'Oils & Ghee',
    sku: 'SKU-OIL-002',
    stock: 3,
    price: 135,
    status: 'LOW STOCK' as const,
    icon: '🛢️',
  },
  {
    id: 'p3',
    name: 'Tata Salt 1kg',
    category: 'Groceries',
    sku: 'SKU-SAL-003',
    stock: 120,
    price: 22,
    status: 'IN STOCK' as const,
    icon: '🧂',
  },
  {
    id: 'p4',
    name: 'Amul Full Cream Milk 500ml',
    category: 'Dairy',
    sku: 'SKU-MLK-004',
    stock: 0,
    price: 30,
    status: 'OUT OF STOCK' as const,
    icon: '🥛',
  },
  {
    id: 'p5',
    name: 'India Gate Basmati Rice 5kg',
    category: 'Rice & Grains',
    sku: 'SKU-RIC-005',
    stock: 28,
    price: 480,
    status: 'IN STOCK' as const,
    icon: '🍚',
  },
  {
    id: 'p6',
    name: 'Tata Tea Premium 500g',
    category: 'Beverages',
    sku: 'SKU-TEA-006',
    stock: 4,
    price: 215,
    status: 'LOW STOCK' as const,
    icon: '🍵',
  },
  {
    id: 'p7',
    name: 'Surf Excel 1kg',
    category: 'Home Care',
    sku: 'SKU-SRF-007',
    stock: 35,
    price: 125,
    status: 'IN STOCK' as const,
    icon: '🧼',
  },
  {
    id: 'p8',
    name: 'Maggi Noodles 70g x12',
    category: 'Instant Food',
    sku: 'SKU-MAG-008',
    stock: 2,
    price: 168,
    status: 'LOW STOCK' as const,
    icon: '🍜',
  },
  {
    id: 'p9',
    name: 'Colgate Max Fresh 200g',
    category: 'Personal Care',
    sku: 'SKU-COL-009',
    stock: 50,
    price: 98,
    status: 'IN STOCK' as const,
    icon: '🪥',
  },
  {
    id: 'p10',
    name: 'Ariel Washing Powder 1kg',
    category: 'Home Care',
    sku: 'SKU-ARI-010',
    stock: 0,
    price: 185,
    status: 'OUT OF STOCK' as const,
    icon: '🧺',
  },
];

export const mockStaff = [
  {
    id: 's1',
    name: 'Rahul Mishra',
    role: 'Cashier',
    attendance: 'Aaya' as const,
    salary: 14000,
    phone: '+91 98765 12345',
    status: 'Active' as const,
    initials: 'RM',
  },
  {
    id: 's2',
    name: 'Pradeep Yadav',
    role: 'Store Manager',
    attendance: 'Aaya' as const,
    salary: 22000,
    phone: '+91 87654 23456',
    status: 'Active' as const,
    initials: 'PY',
  },
  {
    id: 's3',
    name: 'Savita Kumari',
    role: 'Stock Keeper',
    attendance: 'Nahi Aaya' as const,
    salary: 12500,
    phone: '+91 76543 34567',
    status: 'On Leave' as const,
    initials: 'SK',
  },
  {
    id: 's4',
    name: 'Ankur Tiwari',
    role: 'Delivery Boy',
    attendance: 'Aaya' as const,
    salary: 10000,
    phone: '+91 65432 45678',
    status: 'Active' as const,
    initials: 'AT',
  },
  {
    id: 's5',
    name: 'Meena Devi',
    role: 'Packer',
    attendance: 'Pending' as const,
    salary: 9500,
    phone: '+91 54321 56789',
    status: 'Active' as const,
    initials: 'MD',
  },
];

export const mockPayments = [
  {
    id: 'pay1', _id: 'pay1',
    date: '26 Apr 2026, 10:30 AM',
    createdAt: '2026-04-26T10:30:00',
    customer: 'Rajesh Kumar',
    customerInitials: 'RK',
    mode: 'UPI' as const,
    amount: 1500,
    status: 'Success' as const,
  },
  {
    id: 'pay2', _id: 'pay2',
    date: '25 Apr 2026, 03:15 PM',
    createdAt: '2026-04-25T15:15:00',
    customer: 'Priya Singh',
    customerInitials: 'PS',
    mode: 'Card' as const,
    amount: 850,
    status: 'Success' as const,
  },
  {
    id: 'pay3', _id: 'pay3',
    date: '25 Apr 2026, 11:00 AM',
    createdAt: '2026-04-25T11:00:00',
    customer: 'Suresh Sharma',
    customerInitials: 'SS',
    mode: 'UPI' as const,
    amount: 3200,
    status: 'Pending' as const,
  },
  {
    id: 'pay4', _id: 'pay4',
    date: '24 Apr 2026, 06:45 PM',
    createdAt: '2026-04-24T18:45:00',
    customer: 'Vikram Patel',
    customerInitials: 'VP',
    mode: 'Wallet' as const,
    amount: 600,
    status: 'Success' as const,
  },
  {
    id: 'pay5', _id: 'pay5',
    date: '23 Apr 2026, 09:00 AM',
    createdAt: '2026-04-23T09:00:00',
    customer: 'Kavitha Rao',
    customerInitials: 'KR',
    mode: 'UPI' as const,
    amount: 1200,
    status: 'Failed' as const,
  },
  {
    id: 'pay6', _id: 'pay6',
    date: '22 Apr 2026, 04:20 PM',
    createdAt: '2026-04-22T16:20:00',
    customer: 'Pooja Mehta',
    customerInitials: 'PM',
    mode: 'Card' as const,
    amount: 2800,
    status: 'Success' as const,
  },
];

export const mockInvoices = [
  {
    id: 'INV-2026-042',
    customer: 'Rajesh Kumar',
    phone: '+91 98765 43210',
    date: '26 Apr 2026',
    dueDate: '10 May 2026',
    amount: 4250,
    gst: 5,
    status: 'Unpaid',
    items: [
      { name: 'Aashirvaad Atta 5kg', qty: 2, price: 245, total: 490 },
      { name: 'Fortune Oil 1L', qty: 5, price: 135, total: 675 },
      { name: 'Tata Salt 1kg', qty: 10, price: 22, total: 220 },
    ],
  },
  {
    id: 'INV-2026-041',
    customer: 'Suresh Sharma',
    phone: '+91 91234 56789',
    date: '25 Apr 2026',
    dueDate: '9 May 2026',
    amount: 15500,
    gst: 5,
    status: 'Paid',
    items: [
      { name: 'India Gate Rice 5kg', qty: 10, price: 480, total: 4800 },
      { name: 'Ariel 1kg', qty: 5, price: 185, total: 925 },
    ],
  },
  {
    id: 'INV-2026-040',
    customer: 'Priya Singh',
    phone: '+91 77654 32109',
    date: '24 Apr 2026',
    dueDate: '8 May 2026',
    amount: 1200,
    gst: 0,
    status: 'Paid',
    items: [
      { name: 'Amul Milk 500ml', qty: 30, price: 30, total: 900 },
      { name: 'Tata Tea 500g', qty: 1, price: 215, total: 215 },
    ],
  },
  {
    id: 'INV-2026-039',
    customer: 'Vikram Patel',
    phone: '+91 99876 54321',
    date: '20 Apr 2026',
    dueDate: '4 May 2026',
    amount: 8900,
    gst: 5,
    status: 'Overdue',
    items: [
      { name: 'Surf Excel 1kg', qty: 20, price: 125, total: 2500 },
      { name: 'Colgate 200g', qty: 15, price: 98, total: 1470 },
    ],
  },
  {
    id: 'INV-2026-038',
    customer: 'Mohan Lal',
    phone: '+91 87654 32198',
    date: '19 Apr 2026',
    dueDate: '3 May 2026',
    amount: 3450,
    gst: 5,
    status: 'Unpaid',
    items: [
      { name: 'Maggi Noodles 12pk', qty: 10, price: 168, total: 1680 },
      { name: 'Tata Salt 1kg', qty: 20, price: 22, total: 440 },
    ],
  },
];

export const mockVouchers = [
  {
    id: 'v1',
    code: 'DIWALI25',
    discount: 25,
    type: 'percentage',
    minOrder: 500,
    maxDiscount: 200,
    used: 45,
    limit: 100,
    expiry: '30 Nov 2026',
    status: 'Active',
    description: 'Diwali Festival Offer - 25% off on min ₹500 order',
  },
  {
    id: 'v2',
    code: 'FIRST100',
    discount: 100,
    type: 'flat',
    minOrder: 300,
    maxDiscount: 100,
    used: 12,
    limit: 50,
    expiry: '31 May 2026',
    status: 'Active',
    description: 'New customer flat ₹100 off',
  },
  {
    id: 'v3',
    code: 'HOLI20',
    discount: 20,
    type: 'percentage',
    minOrder: 400,
    maxDiscount: 150,
    used: 100,
    limit: 100,
    expiry: '15 Mar 2026',
    status: 'Expired',
    description: 'Holi Special - 20% discount',
  },
  {
    id: 'v4',
    code: 'WEEKEND50',
    discount: 50,
    type: 'flat',
    minOrder: 200,
    maxDiscount: 50,
    used: 8,
    limit: 200,
    expiry: '31 Dec 2026',
    status: 'Active',
    description: 'Weekend special - ₹50 flat off',
  },
];

export const mockCommunityPosts = [
  {
    id: 'post1',
    author: 'Ravi Electronics',
    avatar: 'RE',
    avatarColor: 'bg-blue-100 text-blue-700',
    location: 'Sadar Bazaar, Delhi',
    time: '2 hours ago',
    content: 'Bhai log! DukanDost ki AI feature ne mere 3 overdue customers ko auto-remind kar diya. ₹12,000 wapas mila ek hafte mein! Bahut kaam ka tool hai! 🎉',
    likes: 48,
    comments: 12,
    category: 'Success Story',
    categoryColor: 'bg-green-100 text-green-700',
    image: null,
  },
  {
    id: 'post2',
    author: 'Sharma Kirana',
    avatar: 'SK',
    avatarColor: 'bg-orange-100 text-orange-700',
    location: 'Chandni Chowk, Delhi',
    time: '5 hours ago',
    content: 'QR code wala feature bahut helpful hai. Ab log cash nahi laate, seedha QR scan kar ke pay karte hain. Transactions track bhi hoti hai automatically!',
    likes: 35,
    comments: 8,
    category: 'Tip',
    categoryColor: 'bg-blue-100 text-blue-700',
    image: null,
  },
  {
    id: 'post3',
    author: 'Modi General Store',
    avatar: 'MG',
    avatarColor: 'bg-purple-100 text-purple-700',
    location: 'Lajpat Nagar, Delhi',
    time: '1 day ago',
    content: 'Bhai koi batao — GST bill kaise banate hain DukanDost mein? Maine try kiya lekin customer ka GSTIN kahan enter karte hain?',
    likes: 12,
    comments: 24,
    category: 'Question',
    categoryColor: 'bg-amber-100 text-amber-700',
    image: null,
  },
  {
    id: 'post4',
    author: 'Aggarwal Grocery',
    avatar: 'AG',
    avatarColor: 'bg-teal-100 text-teal-700',
    location: 'Karol Bagh, Delhi',
    time: '2 days ago',
    content: 'Is mahine ₹3.8 lakh ki bikri! Inventory track karne se pata chala kaunsa item sabse zyada bika. Aata aur Tel top 2 rhe. Reorder timing set kar li humne.',
    likes: 92,
    comments: 18,
    category: 'Success Story',
    categoryColor: 'bg-green-100 text-green-700',
    image: null,
  },
];

export const mockOrders = [
  {
    id: 'ORD-001',
    customer: 'Radha Krishnan',
    phone: '+91 99887 66554',
    items: '3 items',
    amount: 785,
    status: 'Pending',
    time: '10:30 AM',
    date: '26 Apr 2026',
    address: '45, Ram Nagar, Sector 5',
  },
  {
    id: 'ORD-002',
    customer: 'Sushma Verma',
    phone: '+91 88776 55443',
    items: '5 items',
    amount: 1240,
    status: 'Confirmed',
    time: '09:15 AM',
    date: '26 Apr 2026',
    address: '12, New Colony, Block B',
  },
  {
    id: 'ORD-003',
    customer: 'Govind Das',
    phone: '+91 77665 44332',
    items: '2 items',
    amount: 450,
    status: 'Delivered',
    time: '11:00 AM',
    date: '25 Apr 2026',
    address: '78, Shastri Nagar, Main Road',
  },
  {
    id: 'ORD-004',
    customer: 'Mamta Tiwari',
    phone: '+91 66554 33221',
    items: '7 items',
    amount: 2100,
    status: 'Delivered',
    time: '04:30 PM',
    date: '25 Apr 2026',
    address: '3, Nehru Park, Near Temple',
  },
  {
    id: 'ORD-005',
    customer: 'Raju Pandit',
    phone: '+91 55443 22110',
    items: '4 items',
    amount: 960,
    status: 'Cancelled',
    time: '12:00 PM',
    date: '24 Apr 2026',
    address: '90, Gandhi Road, Old Market',
  },
];

export const monthlyRevenueData = [
  { name: 'Nov', revenue: 145000, expenses: 95000, profit: 50000 },
  { name: 'Dec', revenue: 182000, expenses: 110000, profit: 72000 },
  { name: 'Jan', revenue: 168000, expenses: 105000, profit: 63000 },
  { name: 'Feb', revenue: 155000, expenses: 98000, profit: 57000 },
  { name: 'Mar', revenue: 196000, expenses: 118000, profit: 78000 },
  { name: 'Apr', revenue: 221000, expenses: 132000, profit: 89000 },
];

export const weeklyChartData = [
  { name: 'Mon', revenue: 18400, expenses: 12000 },
  { name: 'Tue', revenue: 22600, expenses: 14200 },
  { name: 'Wed', revenue: 15800, expenses: 11500 },
  { name: 'Thu', revenue: 27800, expenses: 15800 },
  { name: 'Fri', revenue: 19200, expenses: 13400 },
  { name: 'Sat', revenue: 35600, expenses: 18200 },
  { name: 'Sun', revenue: 28900, expenses: 16800 },
];

export const categoryData = [
  { name: 'Groceries', value: 38 },
  { name: 'Dairy', value: 18 },
  { name: 'Oils & Ghee', value: 15 },
  { name: 'Personal Care', value: 12 },
  { name: 'Home Care', value: 10 },
  { name: 'Others', value: 7 },
];
