import jsPDF from 'jspdf';
import 'jspdf-autotable';

declare module 'jspdf' {
  interface jsPDF {
    autoTable: any;
  }
}

export const generateInvoicePDF = (invoice: any) => {
  const doc = new jsPDF();
  const date = new Date(invoice.createdAt).toLocaleDateString('en-IN');

  // Brand Header
  doc.setFillColor(255, 107, 0); // #FF6B00
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('DukanDost Pro', 15, 25);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Professional Billing & Ledger', 15, 32);

  // Invoice Details Header
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(20);
  doc.text('INVOICE', 155, 60);
  
  doc.setFontSize(10);
  doc.text(`Invoice #: ${invoice.invoiceNumber}`, 155, 68);
  doc.text(`Date: ${date}`, 155, 74);
  doc.text(`Status: ${invoice.status.toUpperCase()}`, 155, 80);

  // Billing Info
  doc.setFont('helvetica', 'bold');
  doc.text('BILL TO:', 15, 60);
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.customerName, 15, 68);
  doc.text(`Phone: ${invoice.customerPhone || 'N/A'}`, 15, 74);
  
  // Table
  const tableData = invoice.items.map((item: any) => [
    item.name,
    item.quantity,
    `INR ${item.price.toFixed(2)}`,
    `INR ${(item.quantity * item.price).toFixed(2)}`
  ]);

  doc.autoTable({
    startY: 95,
    head: [['Item Name', 'Qty', 'Price', 'Total']],
    body: tableData,
    headStyles: { fillColor: [255, 107, 0], textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: [250, 250, 250] },
    margin: { left: 15, right: 15 },
  });

  // Summary
  const finalY = (doc as any).lastAutoTable.finalY + 10;
  
  doc.setFont('helvetica', 'bold');
  doc.text('Summary', 140, finalY);
  doc.setFont('helvetica', 'normal');
  doc.text(`Subtotal:`, 140, finalY + 8);
  doc.text(`INR ${invoice.totalAmount.toFixed(2)}`, 175, finalY + 8);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`TOTAL:`, 140, finalY + 18);
  doc.text(`INR ${invoice.totalAmount.toFixed(2)}`, 175, finalY + 18);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Thank you for your business!', 105, 280, { align: 'center' });
  doc.text('Generated by DukanDost Pro — Your Digital Shop Companion', 105, 285, { align: 'center' });

  // Save
  doc.save(`Invoice_${invoice.invoiceNumber}.pdf`);
};
